// Sentinel Comics Issue #404: Lock Down
// Crafting Aid

const craftingItems = [
  //! Chemical Crafting
  {
    itemName: "Coffee",
    craftingWord: "Active",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 1,
    actionTime: "Power",
    damageType: "",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 1,
    backlash: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "Power – Direct (1 effect to 1 target)",
  },
  {
    itemName: "Amazonian Flowers",
    craftingWord: "Continuous",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 3,
    actionTime: "Ongoing",
    damageType: "Buff",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 1,
    backlash: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "Ongoing – Buff (+1 effect)",
  },
  {
    itemName: "Sodium",
    craftingWord: "Crystalized",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 2,
    actionTime: "Power",
    damageType: "Armor",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 2,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "Power – Armor (-1 effect received for 2 turns)",
  },
  {
    itemName: "Grease",
    craftingWord: "Lubricant",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 2,
    actionTime: "Power",
    damageType: "Buff",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 1,
    backlash: 0,
    turns: 2,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "Power – Buff (+1 effect to 1 target for 2 turns)",
  },
  {
    itemName: "Formaldihide",
    craftingWord: "Preserving",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 5,
    actionTime: "Ongoing",
    damageType: "Armor",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "Ongoing – Armor (-1 effect received)",
  },
  {
    itemName: "Ammonia",
    craftingWord: "Product",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 4,
    actionTime: "End",
    damageType: "",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 1,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "End - Direct (1 effect to 1 target)",
  },
  {
    itemName: "Chlorine",
    craftingWord: "Reactant",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 4,
    actionTime: "Start",
    damageType: "",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 1,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "Start - Direct (1 effect to 1 target)",
  },
  {
    itemName: "Ethanol",
    craftingWord: "Residual",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 3,
    actionTime: "Reaction",
    damageType: "",
    uses: "1 encounter or 10 minutes",
    potency: 1,
    targets: 1,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect: "Reaction - Direct (1 effect to 1 target)",
  },
  {
    itemName: "Ethanol",
    craftingWord: "Spasmodic",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 4,
    actionTime: "Reaction",
    damageType: "Redirect",
    uses: "1 encounter or 10 minutes",
    potency: 2,
    targets: 1,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect:
      "Reaction - Redirect (Redirect the next 2+potency effect to target)",
  },
  {
    itemName: "Sulfuric Acid",
    craftingWord: "Acidic",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 3,
    actionTime: "",
    damageType: "Toxic",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Growth Hormones",
    craftingWord: "Coagulated",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 1,
    actionTime: "",
    damageType: "Melee",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Abiotic",
    craftingWord: "Corrupted",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 3,
    actionTime: "",
    damageType: "Infernal",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Paint Thinner",
    craftingWord: "Debilitating",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 4,
    actionTime: "",
    damageType: "Debuff",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 1,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "Debuff (-1 damage for 1 turn, Direct only)",
  },
  {
    itemName: "Purified Water",
    craftingWord: "Distilled",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 3,
    actionTime: "",
    damageType: "Radiant",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "AntiFreeze",
    craftingWord: "Endothermic",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 2,
    actionTime: "",
    damageType: "Cold",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Glycerol",
    craftingWord: "Exothermic",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 2,
    actionTime: "",
    damageType: "Energy",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Tobacco",
    craftingWord: "Flammable",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 2,
    actionTime: "",
    damageType: "Fire",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Iodine",
    craftingWord: "Galvanic",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 2,
    actionTime: "",
    damageType: "Lightning",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Ink",
    craftingWord: "Injected",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 1,
    actionTime: "",
    damageType: "Projectile",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Crystalized Myelin",
    craftingWord: "Neural",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 3,
    actionTime: "",
    damageType: "Psychic",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Acitone",
    craftingWord: "Pulsating",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 3,
    actionTime: "",
    damageType: "Sonic",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Chemical X",
    craftingWord: "Supersaturated",
    craftingType: "Chemical",
    itemType: "varies",
    craftingNumber: 6,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "Player may add any 1 Crafting Word of their choice to the Mixture",
  },
  {
    itemName: "Honey",
    craftingWord: "Sweet",
    craftingType: "Chemical",
    itemType: "Compound",
    craftingNumber: 4,
    actionTime: "",
    damageType: "Healing",
    uses: 0,
    potency: 0,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "",
  },
  {
    itemName: "Industrial Cleaner",
    craftingWord: "Alkaline",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 2,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 1,
    effect: "Potency +1, Backlash +1 when consumed",
  },
  {
    itemName: "Caster Oil",
    craftingWord: "Concentrated",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 2,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 0,
    targets: 1,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "Targets +1",
  },
  {
    itemName: "Cloroform",
    craftingWord: "Congealed",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 2,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 1,
    effect: "Potency +1, Backlash +1 when consumed",
  },
  {
    itemName: "Laughing Gas",
    craftingWord: "Convulsive",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 1,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 2,
    effect: "Potency +1, Backlash +2 when consumed",
  },
  {
    itemName: "Oil",
    craftingWord: "Crude",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 1,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 2,
    consumedBacklash: 0,
    effect: "Potency +1, Collateral Damage +2 on Power",
  },
  {
    itemName: "Aerosol",
    craftingWord: "Dehydrated",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 1,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 1,
    targets: 25,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "Potency +1, Targets Everyone",
  },
  {
    itemName: "Nitro Glycerine",
    craftingWord: "Explosive",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 2,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 2,
    targets: 25,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 3,
    effect: "Potency +2, Targets Everyone, Backlash +3 when consumed",
  },
  {
    itemName: "Turpentine",
    craftingWord: "Hazardous",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 3,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 2,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 3,
    consumedBacklash: 0,
    effect: "Potency +2, Collateral Damage +3 on Power",
  },
  {
    itemName: "Methanol",
    craftingWord: "Ionic",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 3,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "Potency +1",
  },
  {
    itemName: "Mutant Fungus",
    craftingWord: "Mutagenic",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 3,
    actionTime: "",
    damageType: "",
    uses: "Permanent",
    potency: -1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 4,
    effect:
      "Potency -1, Backlash +4 when consumed, effect is permanent, gains the [Extract] tag.  (Spite nets +0 Potency)",
  },
  {
    itemName: "Adrenaline",
    craftingWord: "Saturated",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 2,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 1,
    consumedBacklash: 0,
    effect: "Potency +1, Collateral Damage +1 on Power",
  },
  {
    itemName: "Saline",
    craftingWord: "Unsaturated",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 2,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: -1,
    targets: 2,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 0,
    effect: "Potency -1, Targets +2",
  },
  {
    itemName: "Liquid Krypton",
    craftingWord: "Unstable",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 2,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 0,
    targets: 1,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 1,
    effect: "Targets +1, Backlash +1 when consumed",
  },
  {
    itemName: "Hydrogen Peroxide",
    craftingWord: "Violent",
    craftingType: "Chemical",
    itemType: "Catalyst",
    craftingNumber: 5,
    actionTime: "",
    damageType: "",
    uses: 0,
    potency: 2,
    targets: 0,
    backlash: 0,
    turns: 0,
    collateralDamage: 0,
    consumedBacklash: 3,
    effect: "Potency +2, Backlash +3 when consumed",
  },

  //! Mechanical Crafting
  /*
  Assisting	Mechanical 1	Frame 	2	Power – Buff (+1 effect to 1 target for 2 turns)
  Automatic	Mechanical 1	Frame 	4	Start - Direct
  Auxiliary	Mechanical 1	Frame 	4	End - Direct
  Cordless	Mechanical 1	Frame 	1	Power – Direct (1 effect to 1 target)
  Personal	Mechanical 1	Frame 	5	Ongoing – Buff (+1 effect)
  Spring-Loaded	Mechanical 1	Frame 	3	Reaction - Direct (1 effect to 1 target)
  Sturdy	Mechanical 1	Frame 	3	Ongoing – Armor (-1 effect received)
  Triggered	Mechanical 1	Frame 	4	Reaction - Redirect (Redirect the next 2+potency effect to target)
  Welding	Mechanical 1	Frame 	2	Power – Armor (-1 effect received for 2 turns)
  Coolant	Mechanical 2	Mechanism 	2	Cold
  Corrosive	Mechanical 2	Mechanism 	3	Toxic
  Digital	Mechanical 2	Mechanism 	2	Energy
  Halogen	Mechanical 2	Mechanism 	3	Radiant
  Inhibitor	Mechanical 2	Mechanism 	4	Debuff (-1 damage for 1 turn, Direct only)
  Irradiated	Mechanical 2	Mechanism 	3	Infernal
  Magnetic	Mechanical 2	Mechanism 	2	Lightning
  Pneumatic	Mechanical 2	Mechanism 	1	Projectile
  Repairing	Mechanical 2	Mechanism 	4	Healing
  Rube-Goldberg	Mechanical	Special	6	Player may add any 1 Crafting Word of their choice to the Device
  Seismic	Mechanical 2	Mechanism 	3	Sonic
  Sharp	Mechanical 2	Mechanism 	1	Melee
  Thermal	Mechanical 2	Mechanism 	2	Fire
  Wireless	Mechanical 2	Mechanism 	3	Psychic
  Bulky	Mechanical 3	Component 	3	Potency +3, gains the [Heavy] tag
  Compressed	Mechanical 3	Component 	3	Potency +1, Uses -1
  Dangerous	Mechanical 3	Component 	1	Potency +1, Targets Everyone, Backlash +2
  Diesel	Mechanical 3	Component 	2	Potency +1, Collateral Damage +1
  Efficient	Mechanical 3	Component 	5	Uses +1
  Golem	Mechanical 3	Component 	X	Unity instead can make a Golem with Health = number of Uses that can Device can be used before it dies (does not work for healing)
  High-Maintenance	Mechanical 3	Component 	1	Potency +1, Collateral Damage +2
  Incandescent	Mechanical 3	Component 	2	Potency +1, Uses -1
  Manual	Mechanical 3	Component 	2	Targets +1
  Module	Mechanical 3	Component 	X	Potency +1, can only be used by Om-X, cannot be Stolen
  Motorized	Mechanical 3	Component 	3	Targets +1
  Overclocked	Mechanical 3	Component 	2	Potency +2, Targets Everyone, Backlash +2, Uses -2
  Precision	Mechanical 3	Component 	6	Device will deal Irreducible damage
  Prototype	Mechanical 3	Component 	4	Potency +2, Uses -2
  Reliable	Mechanical 3	Component 	3	Potency -1, Uses +1
  Rigid	Mechanical 3	Component 	3	Potency +1
  Ruinous	Mechanical 3	Component 	2	Potency +2, Backlash +3 
  Supercharged	Mechanical 3	Component 	3	Potency +2, Collateral Damage +3
  Targeting	Mechanical 3	Component 	2	Potency -1, Targets +2
  User-Friendly	Mechanical 3	Component 	2	Potency +1, Self Only
  Vibrating	Mechanical 3	Component 	1	Potency +1, Backlash +2
  Virtual	Mechanical 3	Component 	6	Uses -2, Uses are now per Combat
  Wind-Up	Mechanical 3	Component 	2	Potency -1, Uses +1
  */
];

export default craftingItems;
