// Sentinel Comics Issue #404: Lock Down
// Crafting Aid

const craftingItems = [
  {
    itemName: "Coffee",
    craftingWord: "Active",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 1,
    actionTime: "Power",
    damageType: "",
    uses: 0,
    potency: 0,
    targets: 1,
    backlash: 0,
    collateralDamage: 0,
    extra: "",
  },
  {
    itemName: "Amazonian Flowers",
    craftingWord: "Continuous",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 3,
    actionTime: "Ongoing",
    damageType: "Buff",
    uses: 0,
    potency: 1,
    targets: 1,
    backlash: 0,
    collateralDamage: 0,
    extra: "",
  },
  {
    itemName: "Sodium",
    craftingWord: "Crystalized",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 2,
    actionTime: "Power",
    damageType: "Armor",
    uses: 0,
    potency: 1,
    targets: 0,
    backlash: 0,
    turns: 2,
    collateralDamage: 0,
    extra: "active for 2 turns",
  },
  {
    itemName: "Sodium",
    craftingWord: "Lubricant",
    craftingType: "Chemical",
    itemType: "Solution",
    craftingNumber: 5,
    actionTime: "Power",
    damageType: "Buff",
    uses: 0,
    potency: 1,
    targets: 1,
    backlash: 0,
    turns: 2,
    collateralDamage: 0,
    extra: "active for 2 turns",
  },
];

export default craftingItems;
